### ISSUE TITLE
Add graphical outputs

### ISSUE THREAD

**Issue by Evpok** [LoicGrobol/ginger#2]
Support exporting a treebank to graphical binary representations.

**Comment by Evpok** [comment]
This is taken care of in the [cairo branch](https://github.com/LoicGrobol/ginger/tree/cairo). Support is planned for
  - svg
  - png
via [cairocffi](https://pypi.python.org/pypi/cairocffi).

**Comment by LoicGrobol** [comment]
Fixed : the cairo branch has been merged
