### ISSUE TITLE
Use schema for input validation

### ISSUE THREAD

**Issue by Evpok** [LoicGrobol/ginger#3]
The current implementations of treebank parsing in `libtreebank` contain a lot of complex copypasta for input validation. using [Schema](https://github.com/keleshev/schema) might make it more DRY and robust.

**Comment by LoicGrobol** [comment]
After some time, this doesn't seem to be very relevant, though using more formally defined parsers e.g. using https://github.com/igordejanovic/Arpeggio or https://github.com/igordejanovic/textX
